<?php

namespace Container53swQfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PFoa1ffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pFoa1ff' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pFoa1ff'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientUserRepository' => ['privates', 'App\\Repository\\ClientUserRepository', 'getClientUserRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordEncoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
        ], [
            'clientUserRepository' => 'App\\Repository\\ClientUserRepository',
            'entityManagerInterface' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
