<?php

namespace Container53swQfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4uT9Y5NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4uT9Y5N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4uT9Y5N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'centerService' => ['privates', 'App\\Services\\CenterService', 'getCenterServiceService', true],
            'client' => ['privates', '.errored..service_locator.4uT9Y5N.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.4uT9Y5N": it references class "App\\Entity\\Client" but no such service exists.'],
            'download' => ['privates', 'App\\Services\\Download', 'getDownloadService', true],
        ], [
            'centerService' => 'App\\Services\\CenterService',
            'client' => 'App\\Entity\\Client',
            'download' => 'App\\Services\\Download',
        ]);
    }
}
