<?php

namespace Container53swQfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Download' shared autowired service.
     *
     * @return \App\Services\Download
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Download.php';

        return $container->privates['App\\Services\\Download'] = new \App\Services\Download();
    }
}
