<?php

namespace ContainerNDkTopy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UuuBLsTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UuuBLsT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UuuBLsT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'centerService' => ['privates', 'App\\Services\\CenterService', 'getCenterServiceService', true],
            'qrcodeService' => ['privates', 'App\\Services\\QrcodeService', 'getQrcodeServiceService', true],
            'user' => ['privates', '.errored..service_locator.UuuBLsT.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.UuuBLsT": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'centerService' => 'App\\Services\\CenterService',
            'qrcodeService' => 'App\\Services\\QrcodeService',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
