<?php

namespace ContainerNDkTopy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCenterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\CenterService' shared autowired service.
     *
     * @return \App\Services\CenterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/CenterService.php';

        return $container->privates['App\\Services\\CenterService'] = new \App\Services\CenterService();
    }
}
