<?php

namespace ContainerNDkTopy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrcodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\QrcodeService' shared autowired service.
     *
     * @return \App\Services\QrcodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/QrcodeService.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/Builder.php';

        return $container->privates['App\\Services\\QrcodeService'] = new \App\Services\QrcodeService(new \Endroid\QrCode\Builder\Builder());
    }
}
