<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_date-io_date-fns_build_index_esm_js-node_modules_material-ui_core_esm_Cs-522381.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
    ],
],

]];
